name: Create a comment on new issue


on:
  issues:
    types: [opened]

jobs:
  comment-with-action: 
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v3
        id: couc
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            My comment

      - name: "dump previous step output"
        run: echo '${{ toJSON(steps.couc.outputs) }}' | jq
        shell: bash


  comment-with-api:
    runs-on: ubuntu-latest
    steps:
      - name: create comment with api
        run: |
          gh api POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${OWNER}/${REPO}/issues/${ISSUE_NUMBER}/comments
          -f body='
            comment from api call
            '
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.event.user.login }}
          REPO: ${{ github.event.repository.name }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
